# TODO Set this up and template neccesary files or look into stylix
[dracula]
[hex]
bg     = "282936"  #282936 #background
base01 = "3a3c4e"  #3a3c4e
base02 = "4d4f68"  #4d4f68
base03 = "626483"  #626483
base04 = "62d6e8"  #62d6e8
fg     = "e9e9f4"  #e9e9f4 #foreground
base06 = "f1f2f8"  #f1f2f8
base07 = "f7f7fb"  #f7f7fb
base08 = "ea51b2"  #ea51b2
base09 = "b45bcf"  #b45bcf
base0A = "00f769"  #00f769
base0B = "ebff87"  #ebff87
base0C = "a1efe4"  #a1efe4
base0D = "62d6e8"  #62d6e8
base0E = "b45bcf"  #b45bcf
base0F = "00f769"  #00f769 